// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CheckVersion():Promise<main.UpdateInfo>;

export function GetDatabases(arg1:string,arg2:string):Promise<Array<string>>;

export function GetTables(arg1:string,arg2:string):Promise<Array<string>>;

export function LoadSettings():Promise<config.Config>;

export function Log(arg1:string):Promise<void>;

export function Logf(arg1:string,arg2:Array<any>):Promise<void>;

export function OpenDownloadUrl(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function StopSync():Promise<void>;

export function SyncDatabase(arg1:Array<string>):Promise<string>;
