// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoUpdate() {
  return window['go']['main']['App']['AutoUpdate']();
}

export function CheckVersion() {
  return window['go']['main']['App']['CheckVersion']();
}

export function DumpAndReplaceDatabase() {
  return window['go']['main']['App']['DumpAndReplaceDatabase']();
}

export function GetDatabases(arg1, arg2) {
  return window['go']['main']['App']['GetDatabases'](arg1, arg2);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function InstallPostgresTools() {
  return window['go']['main']['App']['InstallPostgresTools']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function Logf(arg1, arg2) {
  return window['go']['main']['App']['Logf'](arg1, arg2);
}

export function OpenDownloadUrl(arg1) {
  return window['go']['main']['App']['OpenDownloadUrl'](arg1);
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopSync() {
  return window['go']['main']['App']['StopSync']();
}

export function SyncDatabase(arg1) {
  return window['go']['main']['App']['SyncDatabase'](arg1);
}
